[package]
name = "portex"
version = "0.2.0"
edition = "2024"
description = "A self-contained, no_std-friendly PE (Portable Executable) file reader/writer library"
license = "MIT"
repository = "https://github.com/coconutbird/portex"
readme = "README.md"
keywords = ["pe", "portable-executable", "windows", "exe", "dll"]
categories = ["parsing", "development-tools"]

[features]
default = ["std"]
std = []

[dependencies]

[lints.clippy]
all = { level = "warn", priority = -1 }
