[package]
name = "portex"
version = "0.2.0"
edition = "2024"
description = "A self-contained, no_std-friendly PE (Portable Executable) file reader/writer library"
license = "MIT"
repository = "https://github.com/coconutbird/portex"
readme = "README.md"
keywords = ["pe", "portable-executable", "windows", "exe", "dll"]
categories = ["parsing", "development-tools"]

[features]
default = ["std"]
std = []

[dependencies]

[lints.rust]
warnings = { level = "deny", priority = -2 }
unused = { level = "deny", priority = -1 }
nonstandard_style = { level = "deny", priority = -1 }
rust_2018_idioms = { level = "deny", priority = -1 }
future_incompatible = { level = "deny", priority = -1 }

[lints.clippy]
correctness = { level = "deny", priority = -1 }
suspicious = { level = "deny", priority = -1 }
style = { level = "deny", priority = -1 }
complexity = { level = "deny", priority = -1 }
perf = { level = "deny", priority = -1 }

[lints.rustdoc]
all = { level = "deny", priority = -1 }
